// <auto-generated />
using FoodOrderApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812165710_SeedMenuItemsAndSetPricePrecision")]
    partial class SeedMenuItemsAndSetPricePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodOrderApi.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic pizza with tomato, mozzarella, and basil.",
                            ImageUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002",
                            Name = "Margherita Pizza",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Grilled patty, lettuce, tomato, and house sauce.",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
                            Name = "Classic Burger",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Crispy salted potato fries.",
                            ImageUrl = "https://images.unsplash.com/photo-1573080496219-bb080dd4f877",
                            Name = "French Fries",
                            Price = 129.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
